CREATE TABLE animals (
    id int,
    name text,
    date_of_birth date,
    escape_attempts int,
    neutered boolean,
    weight_kg decimal,
    PRIMARY KEY(id)
);

ALTER TABLE animals ADD species VARCHAR(100);

-- Add new tables and modify the old table

CREATE TABLE owners (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  (START WITH 1 INCREMENT BY 1),
  full_name VARCHAR(100),
  age INT
);

CREATE TABLE species (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  (START WITH 1 INCREMENT BY 1),
  name VARCHAR(100)
);

ALTER TABLE animals 
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
  (START WITH 1 INCREMENT BY 1);

ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals ADD species_id INT;
ALTER TABLE animals ADD FOREIGN KEY (species_id) REFERENCES species (id) ON DELETE CASCADE;

ALTER TABLE animals ADD owner_id INT;
ALTER TABLE animals ADD FOREIGN KEY (owner_id) REFERENCES owners (id) ON DELETE CASCADE;
